version: "1.0.0"
services:
  comics:
    container_name: avd
    image: inpiniti/avd:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
